services:

  server:
    container_name: dev-backend
    build:
      context: ./server
      dockerfile: Dockerfile
      target: dev
    ports:
    - 5000:5000
    networks:
      - todo-net
  mongo:
    image: mongo:7
    container_name: node-todo-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - todo-net
      
volumes:
  mongo-data:

networks:
  todo-net:
    driver: bridge