---
# Backend Services (ClusterIP)
apiVersion: v1
kind: Service
metadata:
  name: todo-svc-backend

spec:
  type: ClusterIP
  selector:
    app: todo-backend
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
      # nodePort: 30090