apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-deployment
  labels:
    app: todo-app

spec:
  replicas: 3
  selector:
    matchLabels:
      app: todo-app

  template:
    metadata:
      labels:
        app: todo-app

    spec:
      containers:

      - name: todo-client
        image: todo-client-prod:latest
        ports:
          - containerPort: 80
      
      - name: todo-server
        image: todo-server-prod:latest
        ports:
          - containerPort: 5000
        env:
        - name: PORT
          value: "5000"
        - name: MONGODB_URI
          value: "mongodb://todo-db-service:27017/node_todo"
        - name: CLIENT_URL
          value: "http://todo-frontend-service:80"
      
      - name: todo-db
        image: mongo:latest
        ports:
          - containerPort: 27017



# PORT=5000
# MONGODB_URI=mongodb://localhost:27017/node_todo
# CLIENT_URL=http://localhost:5173