name: Build and Push Server Image
run-name: ${{ github.actor }} Building Server

on: 
  push:
    branches: [main]
    paths:
      - server/**

jobs:
  build-server:
    
    runs-on: ubuntu-latest
    steps: 
    - uses: actions/checkout@v4

    - name: Create new Tag at ENV
      run: |
        echo "TAG=$(git rev-parse --short HEAD)" >> $GITHUB_ENV

    - name: Log in to Docker Hub
      uses: docker/login-action@v4
      with:
        username: ${{ secrets.DOCKER_USER }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v4

    - name: Build and push
      uses: docker/build-push-action@v7
      with:
        context: ./server
        push: true
        tags: ${{ secrets.DOCKER_USER }}/${{ secrets.REPO_SERVER }}:${{ env.TAG }}

    - name: Checkout Manifest
      uses: actions/checkout@v4
      with:
        ref: manifest
        path: k8s
    
    - name: Modify server deployment
      run: |
        sed -i \
        "s|${{ secrets.DOCKER_USER }}/${{ secrets.REPO_SERVER }}:.*| \
         ${{ secrets.DOCKER_USER }}/${{ secrets.REPO_SERVER }}:${{ env.TAG }}|" \
         k8s/manifest/deployments/server-deployment.yml 

    - name: Push (server) Manifest File to GitHub
      run: |
        cd k8s 
        git config user.email ${{ secrets.EMAIL }}
        git config user.name readoy-cse
        git add .
        git commit -m "Backend deploy tag ${{ env.TAG }}"
        git push -u origin manifest
        tree manifest